# DataX Web Go 配置文件

# 数据库配置
db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: your_pass
  name: datax_web

# 会话密钥
session_key: change-me-very-secret

# 服务器端口
port: 8000

# DataX 安装目录
datax_home: /opt/datax

# 临时文件目录（DataX 作业配置文件存放位置）
temp_dir: /tmp/datax-web