# DataX Web 配置文件
server:
  port: "8000"
  host: "0.0.0.0"

database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "your_pass"
  name: "datax_web"

logging:
  level: "INFO"

datax:
  home: "/opt/datax"
  temp_dir: "/tmp/datax-web"

session:
  key: "your-secret-session-key-change-in-production"